name: Deploy Nginx to Minikube on EC2

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Terraform Init & Apply
      working-directory: ./terraform
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        terraform init
        terraform apply -auto-approve -var="key_name=${{ secrets.AWS_KEY_NAME }}"

    - name: Get EC2 IP
      id: get_ip
      working-directory: ./terraform
      run: echo "INSTANCE_IP=$(terraform output -raw instance_ip)" >> $GITHUB_ENV

    - name: Setup SSH
      run: |
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > private.pem
        chmod 600 private.pem

    - name: Deploy Nginx
      run: |
        ssh -o StrictHostKeyChecking=no -i private.pem ubuntu@${{ env.INSTANCE_IP }} <<'EOF'
        kubectl apply -f https://raw.githubusercontent.com/${{ github.repository }}/main/manifests/nginx-deployment.yaml
        kubectl get pods -A
        EOF
